name: Christian Cito
url: http://christiancito.com
author: Christian Cito
description: Web Developer, Computer Science Student, Avid reader.
title: Christian Cito

twitter: cito_christian
github: christiancito
